version: "3.9"

services:
  db:
    image: postgres:14
    container_name: music_postgres
    restart: always
    environment:
      POSTGRES_DB: musicdb
      POSTGRES_USER: musicuser
      POSTGRES_PASSWORD: musicpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: music_controller_web
    environment:
      DB_NAME: musicdb
      DB_USER: musicuser
      DB_PASSWORD: musicpass
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
