# Generated by Django 4.2.17 on 2025-03-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
        ('spotify', '0002_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='SkipVote',
        ),
    ]
