# Generated by Django 4.2.20 on 2025-04-01 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_room_current_song"),
        ("spotify", "0003_rename_vote_skipvote"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviousVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("song_id", models.CharField(max_length=50)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.room"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "room", "song_id")},
            },
        ),
    ]
