# Generated by Django 4.2.20 on 2025-05-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCharts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('rank', models.IntegerField()),
                ('track_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('spotify_url', models.CharField(max_length=500)),
                ('retrieved_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'top_charts',
            },
        ),
    ]
