# Generated by Django 4.2.20 on 2025-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_topcharts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topcharts',
            old_name='track_name',
            new_name='song_name',
        ),
        migrations.AddField(
            model_name='topcharts',
            name='track_id',
            field=models.CharField(default='temp-id', max_length=255),
        ),
    ]
