# Generated by Django 4.2.20 on 2025-05-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_track_name_topcharts_song_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topcharts',
            options={'managed': False},
        ),
    ]
