# Generated by Django 4.2.21 on 2025-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_topcharts_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['host'], name='idx_room_host'),
        ),
    ]
