# Generated by Django 5.2.3 on 2025-06-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_idx_room_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topcharts',
            options={'managed': True},
        ),
    ]
