# Generated by Django 5.2.3 on 2025-06-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_topcharts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topcharts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
