name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Node dependencies
      run: |
        if [ -f package.json ]; then npm install; fi

    - name: Run Python tests
      run: |
        if [ -f manage.py ]; then python manage.py test; fi

    - name: Run frontend build (optional)
      run: |
        if [ -f package.json ]; then npm run build; fi
